const copy = {
  de: { language: 'Sprache', close: 'Schließen', more: 'Weitere Informationen →', noDescription: 'Keine Beschreibung vorhanden.', programme: 'Zoo-Programm', events: 'Veranstaltungen', showOnMap: 'Auf der Karte zeigen', noEvents: 'Keine Veranstaltungen', noEventsText: 'Zurzeit sind keine Termine für Besucher veröffentlicht.', nextEvent: 'Nächster Termin', clock: 'Uhr' },
  en: { language: 'Language', close: 'Close', more: 'More information →', noDescription: 'No description available.', programme: 'Zoo programme', events: 'Events', showOnMap: 'Show on map', noEvents: 'No events', noEventsText: 'There are currently no published events.', nextEvent: 'Next event', clock: '' },
  nl: { language: 'Taal', close: 'Sluiten', more: 'Meer informatie →', noDescription: 'Geen beschrijving beschikbaar.', programme: 'Zooprogramma', events: 'Evenementen', showOnMap: 'Op de kaart tonen', noEvents: 'Geen evenementen', noEventsText: 'Er zijn momenteel geen gepubliceerde evenementen.', nextEvent: 'Volgende evenement', clock: 'uur' },
  pl: { language: 'Język', close: 'Zamknij', more: 'Więcej informacji →', noDescription: 'Brak opisu.', programme: 'Program zoo', events: 'Wydarzenia', showOnMap: 'Pokaż na mapie', noEvents: 'Brak wydarzeń', noEventsText: 'Obecnie nie ma opublikowanych wydarzeń.', nextEvent: 'Najbliższe wydarzenie', clock: '' },
  fr: { language: 'Langue', close: 'Fermer', more: 'Plus d’informations →', noDescription: 'Aucune description disponible.', programme: 'Programme du zoo', events: 'Événements', showOnMap: 'Afficher sur la carte', noEvents: 'Aucun événement', noEventsText: 'Aucun événement n’est actuellement publié.', nextEvent: 'Prochain événement', clock: '' },
  es: { language: 'Idioma', close: 'Cerrar', more: 'Más información →', noDescription: 'No hay descripción disponible.', programme: 'Programa del zoo', events: 'Eventos', showOnMap: 'Mostrar en el mapa', noEvents: 'No hay eventos', noEventsText: 'Actualmente no hay eventos publicados.', nextEvent: 'Próximo evento', clock: '' },
  it: { language: 'Lingua', close: 'Chiudi', more: 'Maggiori informazioni →', noDescription: 'Nessuna descrizione disponibile.', programme: 'Programma dello zoo', events: 'Eventi', showOnMap: 'Mostra sulla mappa', noEvents: 'Nessun evento', noEventsText: 'Al momento non ci sono eventi pubblicati.', nextEvent: 'Prossimo evento', clock: '' },
  da: { language: 'Sprog', close: 'Luk', more: 'Flere oplysninger →', noDescription: 'Ingen beskrivelse tilgængelig.', programme: 'Zoo-program', events: 'Arrangementer', showOnMap: 'Vis på kortet', noEvents: 'Ingen arrangementer', noEventsText: 'Der er ingen offentliggjorte arrangementer i øjeblikket.', nextEvent: 'Næste arrangement', clock: '' },
} as const

export type VisitorCopy = { [K in keyof typeof copy.de]: string }
export function visitorCopy(locale: string): VisitorCopy { return copy[locale as keyof typeof copy] ?? copy.de }
