// Demo species: id, scientific name, DE/EN names, DE/EN region, DE/EN diet, DE/EN behaviour.
export const groups = {
 aquarium: [
 ['blue-damselfish','Chrysiptera cyanea','Blauer Riffbarsch','Blue Damselfish','Indopazifik','Indo-Pacific','Plankton & Algen','Plankton & algae','Seine leuchtend blaue Färbung fällt zwischen den Korallen auf. In Felsspalten findet dieser kleine Riffbewohner Schutz.','Its vivid blue colour stands out among corals. This small reef fish finds shelter in rocky crevices.'],
 ['clownfish','Amphiprion ocellaris','Falscher Clownfisch','Ocellaris Clownfish','Indopazifik','Indo-Pacific','Kleine Wirbellose','Small invertebrates','Die weißen Bänder sind gut zu erkennen. In der Natur bieten Seeanemonen dem Clownfisch Schutz zwischen ihren Tentakeln.','Its white bands are easy to recognise. In the wild, sea anemones provide shelter among their tentacles.'],
 ['yellow-tang','Zebrasoma flavescens','Gelber Segelflossendoktor','Yellow Tang','Pazifik','Pacific Ocean','Algen','Algae','Dieser leuchtend gelbe Doktorfisch weidet Algen von festen Oberflächen ab. Sein flacher Körper hilft ihm, sich im Riff zu bewegen.','This bright yellow tang grazes algae from hard surfaces. Its flattened body helps it move through a reef.'],
 ['lionfish','Pterois volitans','Rotfeuerfisch','Red Lionfish','Indopazifik','Indo-Pacific','Fische & Krebse','Fish & crustaceans','Gestreifte Flossenstrahlen machen den Feuerfisch unverwechselbar. Einige seiner Flossenstacheln sind giftig.','Striped fin rays make the lionfish distinctive. Some of its fin spines are venomous.'],
 ['seahorse','Hippocampus kuda','Gelbes Seepferdchen','Yellow Seahorse','Indopazifik','Indo-Pacific','Kleine Krebstiere','Small crustaceans','Mit dem Greifschwanz hält sich das Seepferdchen fest. Das Männchen trägt die Eier in einer Bruttasche.','The seahorse anchors itself with its prehensile tail. The male carries the eggs in a brood pouch.'],
 ['cardinalfish','Pterapogon kauderni','Banggai-Kardinalbarsch','Banggai Cardinalfish','Indonesien','Indonesia','Kleine Krebstiere','Small crustaceans','Schwarze Bänder und helle Punkte zeichnen diesen Fisch aus. Das Männchen schützt die Eier in seinem Maul.','Black bands and pale spots distinguish this fish. The male protects the eggs inside its mouth.'],
 ],
 terrarium: [
 ['jeweled-lizard','Timon lepidus','Perleidechse','Ocellated Lizard','Südwesteuropa','Southwest Europe','Wirbellose & Früchte','Invertebrates & fruit','Die Perleidechse trägt auffällige Flecken an den Körperseiten. Sie nutzt sonnige Plätze zum Aufwärmen und zieht sich bei Bedarf in den Schatten zurück.','The ocellated lizard has distinctive spots along its sides. It warms itself in sunny places and retreats into shade when needed.'],
 ['leopard-gecko','Eublepharis macularius','Leopardgecko','Leopard Gecko','Südasien','South Asia','Insekten','Insects','Der Leopardgecko wird vor allem in der Dämmerung aktiv. Im kräftigen Schwanz speichert er Fettreserven.','The leopard gecko is mainly active around dusk. It stores fat reserves in its thick tail.'],
 ['bearded-dragon','Pogona vitticeps','Streifenbartagame','Central Bearded Dragon','Australien','Australia','Pflanzen & Insekten','Plants & insects','Diese Echse stammt aus trockenen Landschaften Australiens. Ihre stachelige Kehle kann sie bei Erregung aufstellen.','This lizard comes from dry Australian landscapes. It can display its spiny throat when aroused.'],
 ['ball-python','Python regius','Königspython','Ball Python','West- & Zentralafrika','West & Central Africa','Kleine Säugetiere','Small mammals','Bei Bedrohung rollt sich der Königspython oft zu einer Kugel zusammen. Diese ungiftige Schlange überwältigt ihre Beute durch Umschlingen.','When threatened, the ball python often curls into a ball. This non-venomous snake subdues its prey by constriction.'],
 ['chameleon','Chamaeleo calyptratus','Jemenchamäleon','Veiled Chameleon','Arabische Halbinsel','Arabian Peninsula','Vorwiegend Insekten','Mainly insects','Greiffüße und ein eingerollter Schwanz helfen beim Klettern. Seine Augen können sich weitgehend unabhängig voneinander bewegen.','Gripping feet and a curled tail help it climb. Its eyes can move largely independently of each other.'],
 ['tortoise','Chelonoidis carbonarius','Köhlerschildkröte','Red-footed Tortoise','Südamerika','South America','Pflanzen & Früchte','Plants & fruit','Rötliche Schuppen schmücken Kopf und Beine dieser Landschildkröte. Ihr Panzer schützt den Körper und ist ein lebender Teil ihres Skeletts.','Reddish scales decorate this tortoise’s head and legs. Its protective shell is a living part of its skeleton.'],
 ],
 'spider-house': [
 ['rose-tarantula','Grammostola rosea','Rote Chile-Vogelspinne','Chilean Rose Tarantula','Chile','Chile','Insekten','Insects','Diese Vogelspinne nutzt geschützte Rückzugsorte am Boden. Feine Sinneshaare helfen ihr, Bewegungen und Erschütterungen wahrzunehmen.','This tarantula uses sheltered retreats on the ground. Fine sensory hairs help it detect movement and vibrations.'],
 ['redknee','Brachypelma hamorii','Mexikanische Rotknie-Vogelspinne','Mexican Red-knee Tarantula','Mexiko','Mexico','Insekten','Insects','Orange-rote Knie heben sich von den dunklen Beinen ab. Die Spinne hält sich häufig nahe ihrem geschützten Unterschlupf auf.','Orange-red knees contrast with its dark legs. This spider often stays close to its sheltered retreat.'],
 ['curlyhair','Tliltocatl albopilosus','Kraushaar-Vogelspinne','Curlyhair Tarantula','Mittelamerika','Central America','Insekten','Insects','Gekräuselte helle Haare verleihen dieser Vogelspinne ihr besonderes Aussehen. Der bodenbewohnende Jäger wartet oft nahe seinem Rückzugsort.','Curled pale hairs give this tarantula its distinctive look. This ground-dwelling hunter often waits near its retreat.'],
 ['greenbottle','Chromatopelma cyaneopubescens','Cyanblaue Vogelspinne','Greenbottle Blue Tarantula','Venezuela','Venezuela','Insekten','Insects','Blaue Beine und ein orangefarbener Hinterleib machen diese Art unverwechselbar. Sie legt ausgedehnte Gespinste um ihren Rückzugsort an.','Blue legs and an orange abdomen make this species distinctive. It builds extensive silk around its retreat.'],
 ['pinktoe','Caribena versicolor','Martinique-Baumvogelspinne','Antilles Pinktoe Tarantula','Martinique','Martinique','Insekten','Insects','Diese baumbewohnende Vogelspinne baut seidene Rückzugsröhren über dem Boden. Ihre Färbung verändert sich während des Heranwachsens deutlich.','This tree-dwelling tarantula builds silken retreats above the ground. Its colour changes considerably as it matures.'],
 ['salmonpink','Lasiodora parahybana','Brasilianische Riesenvogelspinne','Brazilian Salmon Pink Birdeater','Brasilien','Brazil','Wirbellose','Invertebrates','Rosafarbene Haare stehen im Kontrast zum dunklen Körper. Trotz ihres englischen Namens frisst diese große Spinne vor allem Wirbellose.','Pinkish hairs contrast with its dark body. Despite its English name, this large spider mainly eats invertebrates.'],
 ],
};
